= Apache HttpComponents Client 5.x API Plugin for Jenkins

This plugin bundles all the components of https://hc.apache.org/httpcomponents-client-5.2.x/index.html[Apache HttpComponents Client 5.2.x] except `httpclient5-win` because of the dependency on jna.
These components can be used by other plugins as a dependency.
It allows managing library updates independently of plugins.

== How to introduce to your plugin

=== Plugins directly depending on httpclient

Replace the dependency to `org.apache.httpcomponents.client5:httpclient5` with the dependency to `apache-httpcomponents-client-5-api`.

* Before:

----
<dependencies>
  ...
  <dependency>
    <groupId>org.apache.httpcomponents.client5</groupId>
    <artifactId>httpclient5</artifactId>
    <version>5.2.1</version>
  </dependency>
  ...
</dependencies>
----

* After:

----
<dependencies>
  ...
  <dependency>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>apache-httpcomponents-client-5-api</artifactId>
    <version>5.2.1-1.0</version>
  </dependency>
  ...
</dependencies>
----

=== Plugins using libraries depending on httpclient

Add the dependency to `apache-httpcomponents-client-5-api` BEFORE any of dependencies to those libraries to force maven to use `httpclient5` declared by `apache-httpcomponents-client-5-api`.

* Before:

----
<dependencies>
  ...
  <dependency>
    <artifactId>somelibrary-using-httpclient5</artifactId>
    <version>1.0.0</version>
  </dependency>
  <dependency>
    <artifactId>anotherlibrary-using-httpclient5</artifactId>
    <version>1.0.0</version>
  </dependency>
  ...
</dependencies>
----

* After:

----
<dependencies>
  ...
  <dependency>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>apache-httpcomponents-client-5-api</artifactId>
    <version>5.2.1-1.0</version>
  </dependency>
  <dependency>
    <artifactId>somelibrary-using-httpclient</artifactId>
    <version>1.0.0</version>
  </dependency>
  <dependency>
    <artifactId>anotherlibrary-using-httpclient</artifactId>
    <version>1.0.0</version>
  </dependency>
  ...
</dependencies>
----

== Release Notes

Release notes are recorded in https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin/releases[GitHub Releases].

== License

* https://opensource.org/licenses/MIT[MIT License] - Plugin codebase
* https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0] - Nested library